src/Web/Controllers/ExpenseController.cs
using ExpenseMgmt.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Web.Controllers;


public class ExpenseController : Controller
{
    private readonly ExpenseMgmtDbContext _context;
    private readonly Microsoft.AspNetCore.Http.ISession session;

    public ExpenseController(ExpenseMgmtDbContext context, Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor)
    {
        //ExpenseController
        _context = context;
        this.session = httpContextAccessor.HttpContext.Session;
    }

    // GET: /<controller>/
    //public IActionResult Index()
    //{
    //    return View();
    //}

    public async Task<IActionResult> Index(User user)
    {
        try
        {
            var expenses = await _context.Expenses
                .Include(e => e.Employee)
                .Include(e => e.Bills)
                .Include(e => e.History.Where(h => h.IsLatest == true))
                .ThenInclude(h => h.ExpenseStatusType).ToListAsync();

            IEnumerable<Expense> expenseQuery = new List<Expense>();

            int userrole = 0;
            int userid = 0;

            if (HttpContext.Session.TryGetValue("UserRole", out var value) &&
                HttpContext.Session.TryGetValue("UserId", out var uid))
            {
                if (BitConverter.IsLittleEndian)
                {
                    Array.Reverse(value);
                    Array.Reverse(uid);
                }
                userrole = BitConverter.ToInt32(value, 0);
                userid = BitConverter.ToInt32(uid, 0);
            }
            if (userrole == 0)
            {
                return Redirect("Home/Index");
            }

            ViewData["userrole"] = userrole;

            List<ExpenseViewModel> expenseDtos = new List<ExpenseViewModel>();

            switch (userrole)
            {
                case 1: // employee
                    expenseQuery = expenses.Where(e => e.CreatedBy == userid);
                    break;
                case 2: // manager
                    expenseQuery = expenses.Where(e => e.Employee.ManagerId == userid).Where(e => e.History.FirstOrDefault().StatusId == 1);
                    break;

                case 3: // accountant
                    expenseQuery = expenses.Where(e => e.History.FirstOrDefault().StatusId == 2);
                    break;

                case 4: // admin - revist this query , for now fetch everything in the system
                    expenseQuery = _context.Expenses;
                    break;
            }

            foreach (var e in expenseQuery)
            {
                string purpose = "";
                int statusId = 0;
                string statusType = "";
                int totalAmount = 0;
                string Remark = "";

                if (e.History == default)
                {
                    purpose = string.Empty;
                    statusId = 1;
                    statusType = "New";
                    Remark = "New";
                }
                else
                {
                    purpose = e.History.FirstOrDefault().Purpose;
                    statusId = e.History.FirstOrDefault().StatusId;
                    statusType = e.History.FirstOrDefault().ExpenseStatusType.Name;
                    Remark = e.History.FirstOrDefault().Remark;
                }

                if (e.Bills == null)
                {
                    totalAmount = 0;
                }
                else
                {
                    totalAmount = e.Bills.Sum(b => b.Amount);
                }


                if (e.History.FirstOrDefault() == default)
                    purpose = string.Empty;
                else
                    purpose = e.History.FirstOrDefault().Purpose;

                expenseDtos.Add(new ExpenseViewModel
                {
                    Id = e.Id,
                    Currency = e.Currency,
                    ModifiedOn = e.ModifiedOn,
                    CreatedByName = e.Employee.FullName,
                    CreatedOn = e.CreatedOn,
                    Purpose = purpose,
                    Status = statusId,
                    StatusType = statusType,
                    TotalAmount = totalAmount,
                    Remark = Remark
                });
            }

            return View(expenseDtos);
        }
        catch (Exception ex)
        {
            ExceptionLogs log = new ExceptionLogs
            {
                CreatedOn = DateTime.Now,
                InnerException = ex.InnerException.Message,
                Message = ex.Message,
                StackTrace = ex.StackTrace,
            };
            _context.ExceptionLogs.Add(log);
            return View();
        }
        finally
        {
            _context.SaveChanges();
        }
    }

    // GET: Expense/Create
    public IActionResult AddorEdit(int id = 0)
    {
        try
        {

            int UserRole = 0;
            if (HttpContext.Session.TryGetValue("roleid", out var value))
            {
                if (BitConverter.IsLittleEndian)
                    Array.Reverse(value);
                UserRole = BitConverter.ToInt32(value, 0);
            }

            if (id == 0)
                return View(new ExpenseViewModel());
            else
            {
                var expense = _context.Expenses.Include(e => e.History
                                .Where(h => h.IsLatest == true)).ThenInclude(h => h.ExpenseStatusType)
                                .Include(e => e.Employee)
                                .Include(e => e.Bills)
                                .SingleOrDefault(e => e.Id == id);

                if (expense == default)
                    return NotFound();

                ExpenseViewModel viewModel = new ExpenseViewModel();

                if (UserRole == 2 && expense.History.FirstOrDefault().StatusId == 1)
                {
                    viewModel = new ExpenseViewModel
                    {
                        Id = expense.Id,
                        CreatedByName = expense.Employee.FullName,
                        CreatedOn = expense.CreatedOn,
                        Currency = expense.Currency,
                        ModifiedOn = expense.ModifiedOn,
                        Purpose = expense.History.FirstOrDefault().Purpose,
                        Status = expense.History.FirstOrDefault().StatusId,
                        StatusType = expense.History.FirstOrDefault().ExpenseStatusType.Name,
                        Remark = string.Empty,
                        TotalAmount = expense.Bills.Sum(b => b.Amount),
                    };
                }
                else
                {
                    viewModel = new ExpenseViewModel
                    {
                        Id = expense.Id,
                        CreatedByName = expense.Employee.FullName,
                        CreatedOn = expense.CreatedOn,
                        Currency = expense.Currency,
                        ModifiedOn = expense.ModifiedOn,
                        Purpose = expense.History.FirstOrDefault().Purpose,
                        Status = expense.History.FirstOrDefault().StatusId,
                        StatusType = expense.History.FirstOrDefault().ExpenseStatusType.Name,
                        Remark = expense.History.FirstOrDefault().Remark,
                        TotalAmount = expense.Bills.Sum(b => b.Amount),
                    };
                }

                return View(viewModel);
            }
        }
        catch (Exception ex)
        {
            ExceptionLogs log = new ExceptionLogs
            {
                CreatedOn = DateTime.Now,
                InnerException = ex.InnerException.Message,
                Message = ex.Message,
                StackTrace = ex.StackTrace,
            };
            _context.ExceptionLogs.Add(log);
            return View();
        }
        finally
        {
            _context.SaveChanges();
        }


    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddorEdit([Bind("Id,Currency,Purpose,Remark")] ExpenseViewModel expenseViewModel, string submit)
    {
        try
        {
            int UserId = 0;
            if (HttpContext.Session.TryGetValue("UserId", out var value))
            {
                if (BitConverter.IsLittleEndian)
                    Array.Reverse(value);
                UserId = BitConverter.ToInt32(value, 0);
            }

            ModelState.Remove("Remark");
            if (ModelState.IsValid)
            {
                if (expenseViewModel.Id == 0)
                {
                    Expense expense = new Expense
                    {
                        Currency = expenseViewModel.Currency,
                        CreatedOn = DateTime.Now,
                        CreatedBy = UserId,
                        ModifiedOn = DateTime.Now,
                    };

                    _context.Expenses.Add(expense);
                    await _context.SaveChangesAsync();

                    ExpensesHistory history = new ExpensesHistory
                    {
                        ExpenseId = expense.Id,
                        CreatedOn = DateTime.Now,
                        StatusId = 1,
                        Purpose = expenseViewModel.Purpose,
                        IsLatest = true,
                        ModifiedOn = DateTime.Now,
                        Remark = "Created by Employee and pending for approval"
                    };

                    _context.ExpensesHistories.Add(history);
                    await _context.SaveChangesAsync();
                }
                else
                {

src/Web/Views/Expense/AddorEdit.cshtml
@model Web.Models.ExpenseViewModel
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Session;
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Create";
    var userrole = 0;
    if (HttpContextAccessor.HttpContext.Session.TryGetValue("UserRole", out byte[]? value))
    {
        if (BitConverter.IsLittleEndian)
        {
            Array.Reverse(value);
        }

        userrole = BitConverter.ToInt32(value, 0);
    }
    bool isNotEmployee = userrole == 1 ? false : true;
    bool isManager = userrole == 2 ? true : false;
}

@if (Model.Id == 0)
{
    <h4>Create Expense Form</h4>
}
else
{
    <h4>Expense Details</h4>
}
<hr />
<div class="col-md-6">
    <form asp-action="AddorEdit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Currency" class="control-label"></label>
            @if (isNotEmployee)
            {
                <input asp-for="Currency" class="form-control" readonly="readonly" />
            }
            else
            {
                <select asp-for="Currency" class="form-control" >
                <option value="INR">INR</option>
                <option value="USD">USD</option>
                <option value="AED">AED</option>
                <option value="PKR">PKR</option>
                </select>
            }
            <span asp-validation-for="Currency" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="TotalAmount" class="control-label"></label>
            <input asp-for="TotalAmount" class="form-control" readonly="readonly" />
        </div>
        <div class="form-group">
            <label asp-for="Purpose" class="control-label"></label>
            @if (isNotEmployee)
            {
                <input asp-for="Purpose" class="form-control" readonly="readonly" />
            }
            else
            {
                <input asp-for="Purpose" class="form-control" />
            }
            <span asp-validation-for="Purpose" class="text-danger"></span>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" readonly="readonly" />
            </div>
            <div class="form-group col-md-6">
                <label asp-for="ModifiedOn" class="control-label"></label>
                <input asp-for="ModifiedOn" class="form-control" readonly="readonly" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StatusType" class="control-label"></label>
            <input asp-for="StatusType" class="form-control" readonly="readonly" />
        </div>
        <div class="form-group">
            <label asp-for="Remark" class="control-label"></label>
            @if (userrole == 2 && Model.Status==1)
            {
                <input asp-for="Remark" class="form-control" />
            }
            <input asp-for="Remark" class="form-control" readonly="readonly" />
        </div>
        <div class="form-row">
            @if (!isNotEmployee)
            {
                <div class="form-group col-md-6">
                    <input type="submit" value="Submit" name="submit" id="submit" class="btn btn-secondary btn-block"  />
                </div>
                if (Model.Id != 0)
                {
                    <div class="form-group col-md-6">
                        <input type="button" value="Add a bill" onclick="location.href='@Url.Action("AddorEditBill", "Expense",  new {id = 0, expenseid = Model.Id})'" class="btn btn-secondary btn-block" />
                    </div>
                }
            }
            @if (userrole == 2)
            {
                <div class="form-group col-md-6">
                    <input type="submit" id="sendback"  name="submit" value="Send Back For Review" class="btn btn-secondary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <input type="submit" id="approve"  name="submit" value="Approve" class="btn btn-secondary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <input type="submit" id="reject"  name="submit" value="Reject" class="btn btn-secondary btn-block" />
                </div>
            }
            @if (Model.Id != 0 && Model.TotalAmount>0)
            {
                <div class="form-group col-md-6">
                    <input type="button" value="List all bills" onclick="location.href='@Url.Action("ListBills", "Expense", new {expenseid = Model.Id})'" class="btn btn-secondary btn-block" />
                </div>
            }
            <div class="form-group col-md-6">
                <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

src/Web/Views/Expense/AddorEditBill.cshtml
@model Web.Models.BillViewModel
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Session;
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Create";
    var userrole = 0;
    if (HttpContextAccessor.HttpContext.Session.TryGetValue("UserRole", out byte[]? value))
    {
        if (BitConverter.IsLittleEndian)
        {
            Array.Reverse(value);
        }

        userrole = BitConverter.ToInt32(value, 0);
    }
    bool isNotEmployee = userrole == 1 ? false : true;
    bool isManager = userrole == 2 ? true : false;
    Model.ExpenseId = Model.ExpenseId == 0 ? int.Parse((string)Url.ActionContext.RouteData.Values["id"]) : Model.ExpenseId;

}

@if (Model.Id == 0)
{
    <h4>Create Bill Form</h4>
}
else
{
    <h4>Bill Details</h4>
}
<hr />

<div class="col-md-6">
    <form asp-action="AddorEditBill">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (TempData["AmountValidationFailed"]!=null && (bool)TempData["AmountValidationFailed"])
        {
            <p class="text-danger">
               Cannot add this bill as total expense exceeds 5000!
            </p>
        }
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="ExpenseId" />
        <div class="form-group">
            <label asp-for="Serial" class="control-label"></label>
            @if (isNotEmployee)
            {
                <input asp-for="Serial" class="form-control" readonly="readonly" />
            }
            else
            {
                <input asp-for="Serial" class="form-control" />
            }
            <span asp-validation-for="Serial" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Amount" class="control-label"></label>
            @if (isNotEmployee)
            {
                <input asp-for="Amount" class="form-control" readonly="readonly" />
            }
            else
            {
                <input asp-for="Amount" class="form-control" />
            }
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Reason" class="control-label"></label>
            @if (isNotEmployee)
            {
                <input asp-for="Reason" class="form-control" readonly="readonly" />
            }
            else
            {
                <input asp-for="Reason" class="form-control" />
            }
            <span asp-validation-for="Reason" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="IncurredOn" class="control-label"></label>
            @if (isNotEmployee)
            {
                <input asp-for="IncurredOn" class="form-control" readonly="readonly" />
            }
            else
            {
                <input asp-for="IncurredOn" class="form-control" />
            }
            <span asp-validation-for="IncurredOn" class="text-danger"></span>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="UploadedOn" class="control-label"></label>
                <input asp-for="UploadedOn" class="form-control" readonly="readonly" />
            </div>
        </div>

        <div class="form-row">
            @if (!isNotEmployee)
            {
                <div class="form-group col-md-6">
                    <input type="submit" value="Submit" class="btn btn-secondary btn-block" />
                </div>
            }
            <div class="form-group col-md-6">
                <input type="button" value="List all bills" onclick="location.href='@Url.Action("ListBills", "Expense", new {id = Model.Id, expenseid = Model.ExpenseId})'" class="btn btn-secondary btn-block" />
            </div>
            <div class="form-group col-md-6">
                <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to Expense List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

src/Web/Views/Expense/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/Web/Views/Expense/History.cshtml
@model IEnumerable<Web.Models.ExpenseHistoryViewModel>
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Session;
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "History";
}

<h4>Expenses List</h4>

<table class="highlight">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Purpose)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Remark)
            </th>
            <th>
                Action Taken On
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpenseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Purpose)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Remark)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
            </tr>
        }
    </tbody>
    <tfoot>

        <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>

    </tfoot>
</table>

src/Web/Views/Expense/Index.cshtml
@model IEnumerable<Web.Models.ExpenseViewModel>
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Session;
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Index";
    int userrole = (int)ViewData["userrole"];
}
@if (userrole == 1)
{
    <h3>Expenses Created by you</h3>
}
else if (userrole == 2)
{
    <h3>Expenses Awaiting Approval</h3>
}
else if (userrole == 3)
{
    <h3>Expenses waiting to be paid</h3>
}
else
{
    <h3>Expenses List</h3>
}

<table class="highlight">
    @if (Model.Count() != 0)
    {
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Currency)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedByName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Purpose)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StatusType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Remark)
                </th>
                @if (userrole == 1)
                {
                    <th>
                        <a asp-action="AddorEdit" class="btn btn-outline-success"><i class="fa fa-plus-square"></i> Add Expense</a>
                    </th>
                }
                else if (userrole == 4)
                {
                    <th>
                        <div class="btn btn-outline-success">@Html.ActionLink("Reports","Index","Reports")</div>
                    </th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Currency)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedByName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Purpose)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StatusType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Remark)
                    </td>
                    <td>
                        @if (userrole == 1)
                        {
                            if (item.Status == 1 || item.Status == 5)
                            {
                                <a asp-action="AddOrEdit" asp-route-id="@item.Id"><i class="fa fa-marker fa-lg"></i></a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Are you sure to delete expense?')"><i class="fa fa-trash-alt fa-lg"></i></a>
                            }
                        }
                        else if (userrole == 2)
                        {
                            <a asp-action="AddOrEdit" asp-route-id="@item.Id"><i class="fa fa-eye"></i></a>
                            @*if (item.Status == 1)
                            {
                                <a asp-action="ManagerApprove" asp-route-id="@item.Id"><i class="fa fa-check fa-lg"></i></a>
                                <a asp-action="Reject" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Are you sure to reject this expense?')"><i class="fa fa-ban fa-lg"></i></a>
                            }*@
                        }
                        else if (userrole == 3)
                        {
                            <a asp-action="AddOrEdit" asp-route-id="@item.Id"><i class="fa fa-eye"></i></a>
                            <a asp-action="Pay" asp-route-id="@item.Id"><i class="fa fa-money fa-lg"></i></a>
                        }
                        else
                        {
                            <a asp-action="AddOrEdit" asp-route-id="@item.Id"><i class="fa fa-eye"></i></a>
                            <a asp-action="History" asp-route-id="@item.Id"><i class="fa fa-history"></i></a>
                        }

                    </td>
                </tr>
            }
        </tbody>
    }
    else
    {
        <tr>No records found</tr>
        <br />
        @if (userrole == 1)
        {
            <tr>
                <a asp-action="AddorEdit" class="btn btn-outline-success"><i class="fa fa-plus-square"></i> Add Expense</a>
            </tr>
        }
    }
</table>

src/Web/Views/Expense/ListBills.cshtml
@model IEnumerable<Web.Models.BillViewModel>
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Session;
@inject IHttpContextAccessor HttpContextAccessor

@{
    //ViewData["Title"] = "Bills List";
    var userrole = 0;
    if (HttpContextAccessor.HttpContext.Session.TryGetValue("UserRole", out byte[]? value))
    {
        if (BitConverter.IsLittleEndian)
        {
            Array.Reverse(value);
        }

        userrole = BitConverter.ToInt32(value, 0);
    }
    bool isNotEmployee = userrole == 1 ? false : true;
    bool isManager = userrole == 2 ? true : false;
    var expenseId = Model.FirstOrDefault() == default ? int.Parse((string)Url.ActionContext.RouteData.Values["expenseid"]) : @Model.FirstOrDefault().ExpenseId;
}

<h3>Bills</h3>

<table class="highlight">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Serial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IncurredOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UploadedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reason)
            </th>
            @if (userrole == 1 && expenseId!=0)
            {
                <th>
                    <a asp-action="AddorEditBill" asp-route-id= "0" asp-route-expenseid= "@expenseId" class="btn btn-outline-success"><i class="fa fa-plus-square"></i> Add Bill</a>
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.ExpenseId)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Serial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IncurredOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UploadedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reason)
                </td>
                <td>
                    @if (userrole == 1)
                    {

                        <a asp-action="AddorEditBill" asp-route-id= "@item.Id" asp-route-expenseid= "@item.ExpenseId"><i class="fa fa-marker fa-lg"></i></a>
                        <a asp-action="DeleteBill" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Are you sure to delete bill?')"><i class="fa fa-trash-alt fa-lg"></i></a>

                    }
                    else
                    {
                        <a asp-action="AddorEditBill" asp-route-id="@item.Id"><i class="fa fa-eye"></i></a>
                    }

                </td>
            </tr>
        }
    </tbody>
    <tfoot>

        <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>

    </tfoot>
</table>